# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"BaseModel": "00_core.ipynb",
         "adam": "06_optimizers.ipynb",
         "handle_interrupt": "00_core.ipynb",
         "Trainer": "00_core.ipynb",
         "DEVICE": "01_utils.ipynb",
         "hasarg": "01_utils.ipynb",
         "quick_stats": "01_utils.ipynb",
         "TorchCallback": "02_callbacks.ipynb",
         "BasicConfig": "02_callbacks.ipynb",
         "StatsHandler": "02_callbacks.ipynb",
         "MetricPrinter": "02_callbacks.ipynb",
         "EarlyStopper": "02_callbacks.ipynb",
         "PerformanceThreshold": "02_callbacks.ipynb",
         "ModelCheckpoint": "02_callbacks.ipynb",
         "MetricHistory": "02_callbacks.ipynb",
         "S3Uploader": "02_callbacks.ipynb",
         "EC2Closer": "02_callbacks.ipynb",
         "ModelUnfreezer": "02_callbacks.ipynb",
         "SchedulerMixin": "02_callbacks.ipynb",
         "CosineLRScheduler": "02_callbacks.ipynb",
         "percent_positive": "03_metrics.ipynb",
         "mean_soft_prediction": "03_metrics.ipynb",
         "std_soft_prediction": "03_metrics.ipynb",
         "batch_size": "03_metrics.ipynb",
         "GRelu": "04_layers.ipynb",
         "JRelu": "04_layers.ipynb",
         "Mish": "04_layers.ipynb",
         "mish": "04_layers.ipynb",
         "ConvBlock": "04_layers.ipynb",
         "ResBlock": "04_layers.ipynb",
         "Vocabulary": "05_nlp.ipynb",
         "back_translate": "05_nlp.ipynb",
         "variable_lr_optimizer": "06_optimizers.ipynb",
         "update_optimizer": "06_optimizers.ipynb"}

modules = ["core.py",
           "utils.py",
           "callbacks.py",
           "metrics.py",
           "layers.py",
           "nlp.py",
           "optimizers.py"]

doc_url = "https://hdmamin.github.io/incendio/"

git_url = "https://github.com/hdmamin/incendio/tree/master/"


def custom_doc_links(name): return None