#AUTOGENERATED! DO NOT EDIT! File to edit: dev/05_augmentations.ipynb (unless otherwise specified).

__all__ = ['back_translate']

#Cell
from textblob import TextBlob

#Cell
def back_translate(text, to, from_lang='en'):
    """
    Parameters
    ----------

    Returns
    -------
    str: Same language and basically the same content as the original text,
        but usually with slightly altered grammar, sentence structure, and/or
        vocabulary.
    """
    return str(
        TextBlob(text)\
        .translate(to=to)\
        .translate(from_lang=to, to=from_lang)
    )